---
- hosts: ben_s0w1 
  collections:
    - ibm.ibm_zos_core
  gather_facts: no

  tasks:
    - name: Transfer file to mainframe PDS dataset
      zos_copy:
        src: MEMBER.cbl
        dest: 'IBMUSER.DBB.COBOL(MEMBER)'
        is_binary: no