# This is the name of the workflow
name: GitHub Artifacts

# This workflow gets triggered manually through the GitHub Actions UI
on: push
    
jobs:
  artifact_create:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create a local file
        run: echo "Hi, I am storing this data in this file, so that I can use this in the subsequent step within this workflow" > file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: file
          path: file.txt

  artifact_download:
    runs-on: ubuntu-latest
    needs: artifact_create
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: file

      - name: Display file content
        run: cat file.txt
