# This is the name of the workflow
name: GitHub Environment

# This workflow gets triggered manually through the GitHub Actions UI
on:
  # Allow manual triggering of the workflow from the GitHub Actions UI
  workflow_dispatch:  
    
jobs:
  # This job is called secrets
  deployment:
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    environment:
      name: z25c
      url: https://github.com

    steps:  
      - name: Print Secret from environment z25c
        run: |
        echo "z25c_userid: ${{ secrets.Z25C_USERID }}"
        echo "z25c_password: ${{ secrets.Z25C_PASSWORD }}"