# This is the name of the workflow
name: GitHub Secrets

# This workflow gets triggered manually through the GitHub Actions UI
on:
  # Allow manual triggering of the workflow from the GitHub Actions UI
  workflow_dispatch:  
    
jobs:
  # This job is called secrets
  secrets:
    # This job runs on the latest version of Ubuntu
    runs-on: ubuntu-latest

    steps:
      - name : Print Secret
        run: |
          echo "z25c-userid: ${{ secrets.Z25C-USERID }}"
          echo "z25c-password: ${{ secrets.Z25C-PASSWORD }}"

      - name: Print Secret as an environmane variable
        run: |
          echo "z25c-userid: $Z25C-USERID"
        env:  
          Z25C-USERID: ${{ secrets.Z25C-USERID }}



